In [1]:
import pandas as pd
import numpy as np

In [2]:
# 載入三個檔案
df_normalized = pd.read_csv('cleaned_IoTPond2_normalized.csv')
df_actual = pd.read_csv('actual_vs_predicted.csv')
df_targets = pd.read_csv('scaled_target_data.csv')

In [3]:
# 檢查維度
shape_normalized = df_normalized.shape
shape_actual = df_actual.shape
shape_targets = df_targets.shape

# 檢查形狀
print('Normalized shape:', shape_normalized)
print('Actual shape:', shape_actual)
print('Target shape:', shape_targets)

Normalized shape: (82099, 8)
Actual shape: (16419, 1)
Target shape: (82099, 1)

<p> 〔截取對應資料〕截取最後 16,419 筆資料來對齊比較 </p>

In [4]:
# 取 Target 最後的16419筆資料
df_targets_last = df_targets[-16419:]
df_targets_last

       fish_weight
65680     0.767289
65681     0.767289
65682     0.767289
65683     0.767289
65684     0.767289
...            ...
82094     1.000000
82095     1.000000
82096     1.000000
82097     1.000000
82098     1.000000

[16419 rows x 1 columns]

In [5]:
# 取 df_normalized 最後的16419筆資料
df_normalized_last = df_normalized[['fish_weight']].tail(16419)
df_normalized_last

       fish_weight
65680     0.767289
65681     0.767289
65682     0.767289
65683     0.767289
65684     0.767289
...            ...
82094     1.000000
82095     1.000000
82096     1.000000
82097     1.000000
82098     1.000000

[16419 rows x 1 columns]

In [6]:
# 印出總和作為快速檢查
print(sum(df_normalized_last['fish_weight']))
print(sum(df_targets_last['fish_weight']))
print(sum(df_actual['Actual']))

14448.878729022834
14448.878729022834
14448.87870205948

In [7]:
# 檢查列數是否一致
if df_actual.shape[0] == df_targets_last.shape[0] == df_normalized_last.shape[0]:
    print('✅ 列數一致')
else:
    print('❌ 列數不一致')

✅ 列數一致

In [8]:
# 列數比較
if len(df_actual) == len(df_targets_last) == len(df_normalized_last):
    print('✅ 列數一致')
else:
    print('❌ 列數不一致')

✅ 列數一致

In [9]:
# 檢查欄位總數是否對應
if df_actual.shape[1] == df_targets_last.shape[1] == df_normalized_last.shape[1]:
    print('✅ 欄位總數一致')
else:
    print('❌ 欄位總數不一致')

✅ 欄位總數一致

In [10]:
# 資料內容比較
def compare_arrays(arr1, arr2, name1, name2):
    if np.allclose(arr1, arr2, atol=1e-6): # 允許微小誤差的比較
        print(f'✅ {name1} 與 {name2} 完全一致（數值相同）')
    else:
        diff = np.abs(arr1 - arr2)
        max_diff = np.max(diff)
        mismatch_count = np.sum(~np.isclose(arr1, arr2, atol=1e-6))
        print(f'❌ {name1} 與 {name2} 不一致。不同筆數: {mismatch_count}, 最大差異: {max_diff}')

In [11]:
compare_arrays(df_actual.values, df_targets_last.values, 'Actual', 'Targets')
compare_arrays(df_actual.values, df_normalized_last.values, 'Actual', 'Normalized')
compare_arrays(df_targets_last.values, df_normalized_last.values, 'Targets', 'Normalized')

✅ Actual 與 Targets 完全一致（數值相同）
✅ Actual 與 Normalized 完全一致（數值相同）
✅ Targets 與 Normalized 完全一致（數值相同）