In [42]:
import pandas as pd
import numpy as np

In [11]:
# 載入三個檔案
df_normalized = pd.read_csv('cleaned_IoTPond2_normalized.csv')
df_features = pd.read_csv('scaled_feature_data.csv')
df_targets = pd.read_csv('scaled_target_data.csv')
# df_normalized

,temperature,turbidity,disolved_oxg,ph,ammonia,nitrate,fish_length,fish_weight
0,0.385621,1.000000,0.109723,0.980555,0.037348,0.068076,0.0,0.0
1,0.394336,1.000000,0.223008,0.980122,0.037348,0.068076,0.0,0.0
2,0.394336,1.000000,0.366606,0.977097,0.037348,0.068076,0.0,0.0
3,0.394336,1.000000,0.202586,0.979691,0.037348,0.067733,0.0,0.0
4,0.385621,1.000000,0.169721,0.994814,0.037348,0.067045,0.0,0.0
...,...,...,...,...,...,...,...,...
82094,0.642702,0.542088,0.164849,0.000000,1.000000,0.471721,1.0,1.0
82095,0.638344,0.528620,0.185775,0.000000,1.000000,0.473956,1.0,1.0
82096,0.640523,0.525253,0.223399,0.000000,1.000000,0.473956,1.0,1.0
82097,0.633987,0.530303,0.158009,0.000000,1.000000,0.473440,1.0,1.0
82098,0.633987,0.535354,0.132634,0.000000,1.000000,0.473440,1.0,1.0

In [30]:
# 檢查維度
shape_normalized = df_normalized.shape
shape_features = df_features.shape
shape_targets = df_targets.shape

# 檢查形狀
print('Normalized shape:', df_normalized.shape)
print('Feature shape:', df_features.shape)
print('Target shape:', df_targets.shape)

Normalized shape: (82099, 8)
Feature shape: (82099, 7)
Target shape: (82099, 1)

In [34]:
# 檢查列數是否一致
if df_normalized.shape[0] == df_features.shape[0] == df_targets.shape[0]:
    print('✅ 列數一致')
else:
    print('❌ 列數不一致')

✅ 列數一致

In [35]:
# 檢查欄位總數是否對應
if df_features.shape[1] + df_targets.shape[1] == df_normalized.shape[1]:
    print('✅ 欄位總數一致')
else:
    print('❌ 欄位總數不一致')

✅ 欄位總數一致

In [36]:
# 顯示欄位名稱
print('\nNormalized columns:', df_normalized.columns.tolist())
print('\nFeature columns:', df_features.columns.tolist())
print('\nTarget columns:', df_targets.columns.tolist())||

Normalized columns: ['temperature', 'turbidity', 'disolved_oxg', 'ph', 'ammonia', 'nitrate', 'fish_length', 'fish_weight']

Feature columns: ['temperature', 'turbidity', 'disolved_oxg', 'ph', 'ammonia', 'nitrate', 'fish_length']

Target columns: ['fish_weight']

In [38]:
# 結果整理
check_results = {
    'normalized_shape': shape_normalized,
    'feature_shape': shape_features,
    'target_shape': shape_targets,
    'rows_match': rows_match,
    'columns_match': cols_match,
    'normalized_columns': normalized_columns,
    'feature_columns': feature_columns,
    'target_columns': target_columns
}
# check_results

In [40]:
# 合併 features + targets
df_combined = pd.concat([df_features, df_targets], axis=1)
df_combined

,temperature,turbidity,disolved_oxg,ph,ammonia,nitrate,fish_length,fish_weight
0,0.385621,1.000000,0.109723,0.980555,0.037348,0.068076,0.0,0.0
1,0.394336,1.000000,0.223008,0.980122,0.037348,0.068076,0.0,0.0
2,0.394336,1.000000,0.366606,0.977097,0.037348,0.068076,0.0,0.0
3,0.394336,1.000000,0.202586,0.979691,0.037348,0.067733,0.0,0.0
4,0.385621,1.000000,0.169721,0.994814,0.037348,0.067045,0.0,0.0
...,...,...,...,...,...,...,...,...
82094,0.642702,0.542088,0.164849,0.000000,1.000000,0.471721,1.0,1.0
82095,0.638344,0.528620,0.185775,0.000000,1.000000,0.473956,1.0,1.0
82096,0.640523,0.525253,0.223399,0.000000,1.000000,0.473956,1.0,1.0
82097,0.633987,0.530303,0.158009,0.000000,1.000000,0.473440,1.0,1.0
82098,0.633987,0.535354,0.132634,0.000000,1.000000,0.473440,1.0,1.0

In [43]:
diff = np.abs(df_normalized.values - df_combined.values)
max_diff = np.max(diff)
if np.allclose(df_normalized.values, df_combined.values, atol=1e-6):
    print('✅ 資料內容完全一致（數值相同）')
else:
    print(f'❌ 資料內容不一致，最大差異值: {max_diff}')

✅ 資料內容完全一致（數值相同）